### ISSUE TITLE
Week 2 Review Ticket - Project Presentation

### ISSUE THREAD

**Issue by kylem314** [kylem314/btbw#10]

**Comment by jm1021** [comment]
User database and management system.  Nice wireframes.   Managing users and roles.  Related their users and roles could be used by their crossover.  Did not discuss sponsor, but question was asked by crossover.

Objective is to teach Java and Spring login systems.

UML diagram looks good and shows key attributes. 

Did not discuss APIs?

Discuss project with other team and integration.  Here API was discussed.

**Comment by akprathipati** [comment]
Very interesting idea, its very smart because its very essential and you will be able to get a lot of customers. 
UML looks great as well; the ideas were very smart. The design on your wire framers are great. 
I think the fact that you are able to teach people make the project even more interesting. 
Overall, I think it was a BRILLIANT idea and I am really keen on how your implementation will be.
